### ISSUE TITLE
Change the hi and low tone beep

### ISSUE THREAD

**Issue by chrobione** [chrobione/Jasper2fork#19]
I think it should be an option to have the system support a voice based response instead of the high pitch beep.

Something like this  
You: Jasper
Jasper: Yes, Or I am Listening.
You: Whats the weather?
Jasper: Checking please wait..

Something in the profile like

passive_ack: "Words you want it to say"
active_ack: "Words you want it to say"

Just a thought

**Comment by KrawallKurt** [comment]
Shouldn't be hard to implement that

**Comment by chrobione** [comment]
So on this here is my thoughts.

Since this is a personal configuration the profile.yml can handle it with something like this:
```
active_stt:
    engine: witai-stt
    active_reply: 'I am listening.'
    active_response: 'Processing..'
```

There should not be a need for translation files for this, as the user types it in the language they want.
